name: mockbug
description: A web app that uses AngularDart Components
version: 0.0.1
# homepage: https://www.example.com

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  ngdart: ^7.0.2
  ngrouter: any

dev_dependencies:
  ngtest: ^4.0.1
  build_runner: ^2.1.7
  build_version: ^2.1.1
  build_test: ^2.1.5
  build_web_compilers: ^3.2.2
  lints: ^2.0.0
  meta: ^1.7.0
  test: ^1.6.3
  mockito: ^5.2.0
  ngpageloader: ^5.0.0-dev.2
